spring.application.name=LifeStyleMatcherProject

# MySQL DB connectionLifestyle@123

spring.datasource.url=jdbc:mysql://localhost:3306/lifestyle_db
spring.datasource.username=lifestyle_user
spring.datasource.password=Lifestyle@123

# JPA settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port (optional)
server.port=8080

#mail connectivity
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lifestylematcher.help@gmail.com
spring.mail.password=hlmhwoyzcngqyumn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web=DEBUG
logging.level.com.ganesh=DEBUG
spring.profiles.active=dev
#spring.profiles.active=prod
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=University


